Resolve missing golang in zsh, added godep to installer.

diff --git a/scripts/apps/go/install b/scripts/apps/go/install
--- a/scripts/apps/go/install
+++ b/scripts/apps/go/install
@@ -1,7 +1,11 @@
-#!/usr/bin/env bash 
+#!/usr/bin/env bash
 
 # https://storage.googleapis.com/golang/go1.8.3.darwin-amd64.pkg
 
 brew install golang
 
 which go &> /dev/null || (echo "go install failed" && exit 1)
+
+go get github.com/tools/godep
+
+which godep &> /dev/null || (echo "godep install failed" && exit 1)
